services:
  backend_api_s1:
    container_name: krakend_api_service1
    image: openjdk:21-slim
    volumes:
      - ./jar:/service/api
    ports:
      - 8001:8003
    command: ["java", "-jar", "/service/api/krakend-api-0.0.1.jar"]


  backend_api_s2:
    container_name: krakend_api_service2
    image: openjdk:21-slim
    volumes:
      - ./jar:/service/api
    ports:
      - 8002:8003
    command: ["java", "-jar", "/service/api/krakend-api-0.0.1.jar"]


  backend_api_s3:
    container_name: krakend_api_service3
    image: openjdk:21-slim
    volumes:
      - ./jar:/service/api
    ports:
      - 8003:8003
    command: ["java", "-jar", "/service/api/krakend-api-0.0.1.jar"]